Tooltips
tj-uav/GroundStation pull request #104
Opened 2022-07-06 01:52 UTC by pizzalemon

Add tooltips to some buttons and data displays, should improve usability. Along with that, deleted Antenna Tracker because that thing isn't going to be implemented. Also a conversion switcher on the actions page for the UAV altitude.

2022-07-06 02:07 UTC, KrishnanS2006 requested changes
Mostly just tooltip wording additions, changes, and fixes. Otherwise LGTM :D

2022-07-06 02:07 UTC, krishnans2006 commented on client/src/pages/FlightData/tabs/Actions.js
> +						<Box label="Ground Speed" content={AgroundSpeed.toFixed(2) + " mph"} title="Speed over only the surface of the earth, not taking height into account." />
Maybe mention that it's GPS speed? That wording is kinda vague...

2022-07-06 02:07 UTC, krishnans2006 commented on client/src/pages/FlightData/tabs/Actions.js
> +					<Button warning={true} color={darkred} onClick={() => httppost("/ugv/sethome")} title="Set the plane home position.">Set home?</Button>
UGV = plane (?)

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +							title="The plane's altitude. MSL refers to above mean sea level. AGL is the height from the ground where the plane is." />
More specifically the home location altitude

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +							title="Speed over only the surface of the earth, not taking height into account." />
Again, mention that it's GPS speed

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +							title="Speed of the plane overall, including change in altitude." />
That's not what airspeed is - it's speed data from sensors on the plane (relative to wind speed)

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +						<Box label="Satellites" content={Aconnection[2].toFixed(0)} title="The number of satellites the plane is using." />
Maybe mention thresholds for proper flight?

4 satellites is the absolute minimum, with 6 being reasonable, 8+ being good, and 10+ being very accurate

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +						<Box label="Ground Speed" content={GgroundSpeed.toFixed(2) + " mph"} title="Speed over only the surface of the earth" />
Again, mention GPS speed

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +						<Box label="Mode" content={Gmode} title="The mode of mission the UGV is in, including RTL, and Auto mode." />
```suggestion
						<Box label="Mode" content={Gmode} title="The mode of mission the UGV is in, including RTL, Hold, and Auto mode." />
```

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/FlightData/tabs/Quick.js
> +						<Box label="Satellites" content={Gconnection[2].toFixed(0)} title="The number of satellites the UGV is using." />
Again, add extra info on satellite count

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/Submissions/Tabs.js
> +						title="Reject the ODLC."
```suggestion
						title="Move the ODLC to a separate list of rejected ODLCs."
```

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/Submissions/toolbarForm.js
> +					<Checkbox type="decline" callback={decline} disabled={disabled} title="Reject the ODLC." />
```suggestion
					<Checkbox type="decline" callback={decline} disabled={disabled} title="Move the ODLC to a separate list of rejected ODLCs." />
```

2022-07-06 02:07 UTC, KrishnanS2006 commented on client/src/pages/Submissions/toolbarForm.js
> +					<Checkbox type="decline" callback={decline} disabled={disabled} title="Reject the ODLC." />
```suggestion
					<Checkbox type="decline" callback={decline} disabled={disabled} title="Move the ODLC to a separate list of rejected ODLCs." />
```

2022-07-07 02:54 UTC, pizzalemon commented on client/src/pages/Submissions/toolbarForm.js
> +					<Checkbox type="decline" callback={decline} disabled={disabled} title="Reject the ODLC." />
I feel that this is well understood.

2022-07-07 23:43 UTC, krishnans2006 approved these changes
👍

2022-07-07 23:59 UTC, merged